### ISSUE TITLE
Does this work with Gedit 3?

### ISSUE THREAD

**Issue by reagle** [jessex/gedit-tables#1]

**Comment by jessex** [comment]
**Unfortunately no**: the update to gedit 3.x broke compatibility with plugins for gedit 2.x (for Python, at least, I don't know about C) as the binding system that is now utilized is [PyGObject](https://live.gnome.org/PyGObject) instead of [PyGTK](http://www.pygtk.org/). To migrate the plugin from PyGTK to PyGObject should not be _too_ time-consuming, but it's non-trivial. 

I do not have any immediate plans to update the plugin to work with gedit 3, but I'll take a further look into it.

**Comment by reagle** [comment]
On Saturday, January 21, 2012, you wrote:

> I do not had any immediate plans to update the plugin to work with gedit 3, but I'll take a further look into it.

OK, I figure I'll be moving to a Gnome 3 based distribution in April and would hate to lose this.

**Comment by jessex** [comment]
> OK, I figure I'll be moving to a Gnome 3 based distribution in April and would hate to lose this.

In that case, I will definitely look into updating the plugin before then. I will update this issue when I get started on that and make progress.

**Comment by reagle** [comment]
On Monday, January 23, 2012, you wrote:

> In that case, I will definitely look into updating the plugin before then. I will update this issue when I get started on that and make progress.

Thanks!

**Comment by jessex** [comment]
No problem at all.

**Comment by reagle** [comment]
btw: why not make the defaults use pandoc grid tables?
  http://johnmacfarlane.net/pandoc/README.html#tables

**Comment by jessex** [comment]
The idea honestly never came to me; that's definitely something to take a look at implementing, though. Thanks!

**Comment by reagle** [comment]
On Tuesday, January 24, 2012, you wrote:

> The idea honestly never came to me; that's definitely something to take a look at implementing, though. Thanks!

The pandoc/markdown and RestructuredText table formats are quite similar -- and I imagine that's what people often use the plug in for.

The only other thing I wish the plugin did was make the table a reasonable width -- and perhaps wrapping text within a cell -- instead of permitting it to be arbitrarily wide.

**Comment by reagle** [comment]
On 01/23/2012 12:21 PM, Joseph Reagle wrote:

> On Monday, January 23, 2012, you wrote:
> 
> > In that case, I will definitely look into updating the plugin before then. I will update this issue when I get started on that and make progress.

btw: I'm using gedit 3 now!

When I need a table, I resort to emacs and table.el, but look forward to 
this still :) .

**Comment by jessex** [comment]
This is not the first time that I've been beaten to the punch by emacs, and it will likely not be the last! But the Gedit 3 version of this plugin is coming soon!

**Comment by jessex** [comment]
Table Maker is now compatible with Gedit 3.x! I've tested it on a few different machines and everything appears to be in working order. There are some more things I'd like to do with the plugin (including some suggestions mentioned earlier in this issue), but I'm closing this out since the plugin is now up-to-date.

**Comment by reagle** [comment]
Thanks, I can confirm the plugin is callable and will create the table, but on my setup (Kubuntu Precise presently) I look my cursor and my ability to edit the document.

urd:~$ gedit
gedit:19429): Gtk-WARNING **: Theme parsing error: gtk.css:58:46: Unknown value 'GTK_SHADOW_NONE' for enum type 'GtkShadowType'

(gedit:19429): Gtk-WARNING **: Theme parsing error: gtk.css:58:46: Unknown value 'GTK_SHADOW_NONE' for enum type 'GtkShadowType'

(gedit:19429): Gtk-WARNING **: Theme parsing error: gtk.css:58:46: Unknown value 'GTK_SHADOW_NONE' for enum type 'GtkShadowType'
TypeError: **init**() takes exactly 3 arguments (1 given)

*\* (gedit:19429): WARNING **: Could not load theme icon gtk-home: Icon 'gtk-home' not present in theme
Traceback (most recent call last):
  File "/home/reagle/.local/share/gedit/plugins/gedittables/**init**.py", line 69, in on_menu_click
    self.dialog.set_transient_for(self.window)
AttributeError: TableDialog instance has no attribute 'set_transient_for'
